commander:
   image: josefuentes/cranecommander
   hostname: cocommander
   container_name: co_commander
   environment:
     - DEBUG=true
     - REDIS=true
   ports:
     - "8888:8888"
   volumes:
     - ./commander/certs:/var/lib/commander/certs
     - ./commander/commander-data-tests/r10k/git:/root/.r10k/git
     - ./commander/commander-data-tests/var/crane:/var/crane/
     # Override application copied with the actual folder mounted as volume.
     # Allows real time changes and log monitoring from editor
     - ./commander/app:/usr/src/commander
   links:
     - redis
     - registry:coregistry
     - engine:coengine
     - emulatedhost
   restart: always
   command: python /usr/src/commander/commander.py


registry:
  extends:
    file: ./registry/compose.yml
    service: registry
  container_name: co_registry
  ports:
      - 5000:5000
  volumes:
    - ./registry/registry-data-tests:/var/lib/registry
  restart: always


engine:
  image: josefuentes/craneengine
  privileged: true
  volumes:
    - /var/lib/docker
    - /lib/modules:/lib/modules
    - ./engine/certs:/var/lib/coengine/certs
  hostname: coengine
  environment:
    - DOCKER_DAEMON_ARGS=--tlsverify --tlscacert=/var/lib/coengine/certs/ca.pem --tlscert=/var/lib/coengine/certs/server-cert.pem --tlskey=/var/lib/coengine/certs/server-key.pem
    - PORT=4243
  container_name: co_engine
  links:
    - registry:coregistry
  restart: always
  command: /root/launch.sh


redis:
  image: redis:3
  container_name: co_redis
  ports:
    - 6379:6379
  restart: always

emulatedhost:
  image: josefuentes/craneengine
  privileged: true
  volumes:
    - /var/lib/docker
    - /lib/modules:/lib/modules
    - ./tests/emulatedhost/certs:/var/lib/emulatedhost/certs
  hostname: emulatedhost
  environment:
    - DOCKER_DAEMON_ARGS=--tlsverify --tlscacert=/var/lib/emulatedhost/certs/ca.pem --tlscert=/var/lib/emulatedhost/certs/emulatedhost-cert.pem --tlskey=/var/lib/emulatedhost/certs/emulatedhost-key.pem
    - PORT=4243
  container_name: co_emulatedhost
  links:
    - registry:coregistry
  restart: always
  command: /root/launch.sh
